load("@aspect_bazel_lib//lib:testing.bzl", "assert_json_matches")
load("@aspect_rules_js//js:defs.bzl", "js_test")
load("@aspect_rules_swc//swc:defs.bzl", "swc")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//examples/generate_swcrc:tsconfig-to-swcconfig/package_json.bzl", tsconfig_to_swcconfig = "bin")

npm_link_all_packages(name = "node_modules")

tsconfig_to_swcconfig.t2s(
    name = "write_swcrc",
    srcs = ["tsconfig.json"],
    args = [
        "--filename",
        "$(location tsconfig.json)",
    ],
    stdout = ".swcrc",
    visibility = ["//:__subpackages__"],
)

# Demonstrate that it works
swc(
    name = "compile",
    srcs = glob(["lib/**", "app/**"]),

    # Generates incorrect import path (see generated app/index.js)
    swcrc = ".swcrc",

    # Generates correct import path
    # swcrc = "my_swcrc",
)

# Verify that our options got passed through
assert_json_matches(
    name = "test",
    file1 = ".swcrc",
    file2 = "tsconfig.json",
    filter1 = ".jsc.target",
    filter2 = ".compilerOptions.target",
)


genrule(
    name = "generate_package_json",
    outs = ["package.json"],
    cmd = """echo '{"type": "module"}' > $@ """,
)

js_test(
    name = "test_compile",
    data = [":compile", ":generate_package_json"],
    entry_point = "app/main.js",
)
